[package]
name = "mgraphrust"
version = "0.1.0"
edition = "2021"
description = "A professional graph visualization and editing library with advanced UX patterns"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mGraphRust/mGraphRust"
keywords = ["graph", "visualization", "editor", "ui", "egui"]
categories = ["gui", "visualization", "graphics"]

[lib]
name = "mgraphrust"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
egui = "0.29"
eframe = { version = "0.29", default-features = false, features = [
    "accesskit",
    "default_fonts",
    "glow",
    "persistence",
] }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.17", features = ["v4", "serde"] }
env_logger = "0.11"
log = "0.4"
chrono = { version = "0.4", features = ["serde"] }
rfd = "0.15"
serde_json = "1.0"
dirs = "6.0"
csv = "1.3"
egui_plot = "0.29"
# Audio processing for morse code
cpal = "0.15"
crossbeam-channel = "0.5"
# Math and random for DLinOSS
rand = "0.8"

[dev-dependencies]
tempfile = "3.13"

[[bin]]
name = "mGraphRust-demo"
path = "src/main.rs"

[[bin]]
name = "morse-test"
path = "src/bin/morse_test.rs"
